import type { NextPage } from 'next'
import Head from 'next/head'
import CardWrap from '../components/card/card-wrap'

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<CardWrap />
			</main>

			<footer></footer>
		</div>
	)
}

export default Home
