import type { NextPage } from 'next'
import Head from 'next/head'
import CardWrap from '../components/card/card-wrap'
import { CommonLinks } from '../components/head/CommonLinks'

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Gitflame</title>
				<meta name="description" content="Generated by create next app" />
				<CommonLinks />
			</Head>
			<main>
				<CardWrap />
			</main>

			<footer></footer>
		</div>
	)
}

export default Home
