import type { NextPage } from 'next'
import Head from 'next/head'
import Card from '../components/card'
import CardWrap from '../components/card/small-card'
import { CommonLinks } from '../components/head/CommonLinks'

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Gitflame</title>
				<meta name="description" content="Generated by create next app" />
				<CommonLinks />
			</Head>
			<main>
				<CardWrap />
				<a href="http://localhost:3000/api/auth/github/signup"> Click here</a>
				<Card />
			</main>

			<footer></footer>
		</div>
	)
}

export default Home
